apiVersion: rbac.authorization.k8s.io/v1  # Updated API version
kind: ClusterRole
metadata:
  name: dex
  namespace: auth
rules:
- apiGroups: ["dex.coreos.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create"]
