apiVersion: v1
kind: ConfigMap
metadata:
  name: pgpool-config
  namespace: postgres
data:
  pgpool.conf: |
    # Add your pgpool configuration here
    # Example:
    pid_file_name = '/opt/bitnami/pgpool/tmp/pgpool.pid'
    listen_addresses = '*'
    port = 5432
    backend_hostname0 = 'postgresql-postgresql-ha-postgresql-0.postgresql-postgresql-ha-postgresql-headless'
    backend_port0 = 5432
    backend_weight0 = 1
    backend_data_directory0 = '/var/lib/postgresql/data'
    backend_flag0 = 'ALLOW_TO_FAILOVER'
    backend_hostname1 = 'postgresql-postgresql-ha-postgresql-0.postgresql-postgresql-ha-postgresql-headless'
    backend_port1 = 5432
    backend_weight1 = 1
    backend_data_directory1 = '/var/lib/postgresql/data'
    backend_flag1 = 'ALLOW_TO_FAILOVER'
    backend_hostname2 = 'postgresql-postgresql-ha-postgresql-2.postgresql-postgresql-ha-postgresql-headless'
    backend_port2 = 5432
    backend_weight2 = 1
    backend_data_directory2 = '/var/lib/postgresql/data'
    backend_flag2 = 'ALLOW_TO_FAILOVER'