argocd-apps:
  applications:
    argocd:
      namespace: argocd
      project: default
      source:
        repoURL: https://github.com/Shasame/KinD-test-cluster.git
        path: argocd/argocd
        targetRevision: path
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
    argocd-apps:
      namespace: argocd
      project: default
      source:
        repoURL: https://github.com/Shasame/KinD-test-cluster.git
        path: argocd/argocd-apps
        targetRevision: path
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
  applicationSets:
    apps:
      generators:
      - git:
          repoURL: https://github.com/Shasame/KinD-test-cluster.git
          revision: path
          directories:
          - path: argocd/apps
      template:
        metadata:
          name: '{{path.basename}}'
          labels:
            project: 'default' 
          annotations: {}
        spec:
          project: default
          source:
            repoURL: https://github.com/Shasame/KinD-test-cluster.git
            targetRevision: path
            path: '{{path}}'
          destination:
            namespace: '{{path.basename}}'
            server: https://kubernetes.default.svc
          syncPolicy:
            automated:
              prune: false
              selfHeal: false
            syncOptions:
            - CreateNamespace=true
            - FailOnSharedResource=true