---
- name: Install Helm
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Download Helm
      get_url:
        url: https://get.helm.sh/helm-v3.14.0-linux-amd64.tar.gz
        dest: /tmp/helm.tar.gz

    - name: Extract Helm
      unarchive:
        src: /tmp/helm.tar.gz
        dest: /tmp

    - name: Move Helm binary
      command: mv /tmp/linux-amd64/helm /usr/local/bin/helm

    - name: Set Helm permissions
      command: chmod +x /usr/local/bin/helm

    - name: Verify Helm installation
      command: helm version