---
- name: Deploy Sample App
  hosts: kubernetes-host
  become: true
  tasks:
    #Build image only if not present
    - name: Check if the image exists
      command: docker images -q my-sample-app
      register: image_exists

    - name: Build the docker image if not present
      when: not image_exists.stdout
      command: docker build -t my-sample-app /mnt/hgfs/MyKube/sampleApp

    - name: Load the image in the Kind cluster
      command: kind load docker-image my-sample-app:latest -n mykube
    
    - name: Create the namespace
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: sample-app

    - name: Deploy to Kubernetes
      k8s:
        namespace: sample-app
        state: present
        definition: "{{ lookup('file', '/mnt/hgfs/MyKube/sampleApp/sampleApp-deployment.yml') }}"
          
    - name: Expose the service
      k8s:
        namespace: sample-app
        state: present
        definition: "{{ lookup('file', '/mnt/hgfs/MyKube/sampleApp/sampleApp-service.yml')}}"